### ISSUE TITLE
安装主题之后，openwrt管理界面打不开

### ISSUE THREAD

**Issue by jx-xysm** [garypang13/luci-theme-edge#1]
安装之后，管理界面打不开，浏览器调试提示
Failed to load resource: the server responded with a status of 404 (Not Found)      zh-cn:1（http://192.168.1.1/cgi-bin/luci/admin/translations/zh-cn?v=2.1）

固件版本 | OpenWrt R20.7.7 / LuCI Master (git-20.191.36863-eee6bae)
内核版本 | 4.19.131

**Comment by kiddin9** [comment]
不好意思,只针对luci19.07版本, 没有适配 luci18.06,也没有适配计划, luci18.06相信很快要被淘汰了,也就是说用lean的固件都不适用.

**Comment by jx-xysm** [comment]
哦，了解了。

**Comment by db-one** [comment]
按照lean的节奏，更新luci19.07估计很会很久了，还是希望可以支持一下18.06

**Comment by kiddin9** [comment]
> 按照lean的节奏，更新luci19.07估计很会很久了，还是希望可以支持一下18.06

已支持18.06

**Comment by db-one** [comment]
> > 按照lean的节奏，更新luci19.07估计很会很久了，还是希望可以支持一下18.06
> 
> 已支持18.06

好的   我去编译试试
