### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by Aes64X** [garypang13/luci-theme-edge#15]
大佬，我更新了昨天，分支18.06

完事儿发现二级菜单都打不开了，直接输入二级地址是可以进去的。

![QQ截图20201122182956](https://user-images.githubusercontent.com/47932152/99901320-ee7ee980-2cf0-11eb-96fc-fe5ef279554a.png)

**Comment by Aes64X** [comment]
![Uploading QQ截图20201122183257.png…]()

**Comment by kiddin9** [comment]
感谢反馈,已修复.

**Comment by Aes64X** [comment]
> 感谢反馈,已修复.

稍后我将测试，多谢修复。
