### ISSUE TITLE
大佬等等。。还有个BUG

### ISSUE THREAD

**Issue by Aes64X** [garypang13/luci-theme-edge#16]
![QQ截图20201122224906](https://user-images.githubusercontent.com/47932152/99907091-c8b80b80-2d15-11eb-85f0-f657bc75fcc0.png)
保留配置的选框无论是否选择都没有任何图形表现。
![QQ截图20201122225627](https://user-images.githubusercontent.com/47932152/99907120-f69d5000-2d15-11eb-9aca-127fa400250d.png)

**Comment by Aes64X** [comment]
18.06分支测试

**Comment by kiddin9** [comment]
已修复.

**Comment by Aes64X** [comment]
> 已修复.

感谢修复
