### ISSUE TITLE
图标不显示，且部分按钮错位

### ISSUE THREAD

**Issue by liyiecho** [garypang13/luci-theme-edge#2]
系统固件版本	OpenWrt SNAPSHOT r13848-5792f6a104 / LuCI Master git-20.186.79919-0c47989
luci-theme-edge版本 7.19
图标不显示（7.17版可以显示），且部分按钮错位，如图所示
<img width="1254" alt="QQ20200719-233057@2x" src="https://user-images.githubusercontent.com/5213722/87878814-49d65d80-ca19-11ea-9534-03cca15b711f.png">

**Comment by kiddin9** [comment]
图标已修复,至于按钮错位我用的是luci 19,07分支并没有问题,难道是luci master才有么,

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/87946473-a3e82900-cad4-11ea-89dd-6b3b55dda0a5.png)
b编译成功之后 打开是空白的  不知道什么情况
![image](https://user-images.githubusercontent.com/20243226/87946521-b82c2600-cad4-11ea-9f5c-8875ba6248bd.png)
源码是大雕的

**Comment by kiddin9** [comment]
大雕的是luci18.06,你要用 https://github.com/garypang13/luci-theme-edge/tree/18.06 这个分支

**Comment by db-one** [comment]
好的  谢谢 我再试试

**Comment by db-one** [comment]
之前看到你说支持18.06了  我以为是直接一套源码支持了 没看到原来是新开了一个分支  辛苦了
