### ISSUE TITLE
请教是否可以固定显示路由器本地的背景图

### ISSUE THREAD

**Issue by touchsola** [garypang13/luci-theme-edge#20]
登陆页面随机显示的背景图片中，由于分辨率关系，有些背景图只显示一个头，或者几根头发，晚上看有点吓人😀

**Comment by apc337** [comment]
是啊，我也想要知道怎么固定背景图，我尝试替换了3张背景图，当时是有效的，结果第二天又变回去了.

**Comment by kiddin9** [comment]
删除 https://github.com/garypang13/luci-theme-edge/blob/5a9a8465dd5e3eb5b526d253ed8c5ef8a7cfd695/luasrc/view/themes/edge/sysauth.htm#L135-L139
这几行,

**Comment by apc337** [comment]
请问修改后，云编译时怎么调用修改后的文件啊？
直接在路由器上修改，删掉的代码第二天又自动变回去了

**Comment by kiddin9** [comment]
在后台 系统设置 中 关闭 自动更新软件包

**Comment by touchsola** [comment]
> 
> 
> 删除
> 
> https://github.com/garypang13/luci-theme-edge/blob/5a9a8465dd5e3eb5b526d253ed8c5ef8a7cfd695/luasrc/view/themes/edge/sysauth.htm#L135-L139
> 
> 这几行,

收到，谢谢您
