### ISSUE TITLE
18.06反馈几个小细节

### ISSUE THREAD

**Issue by db-one** [garypang13/luci-theme-edge#3]
![image](https://user-images.githubusercontent.com/20243226/88002975-5bf9ee00-cb36-11ea-925c-10a06d93f3b0.png)

![image](https://user-images.githubusercontent.com/20243226/88002663-9f079180-cb35-11ea-919b-324d6f1aae56.png)
这里进度条没有效果，另外。红蓝的条纹格子感觉有点突兀，如果可以弱化一下就更好了
![image](https://user-images.githubusercontent.com/20243226/88002712-ba729c80-cb35-11ea-83aa-375ec4e4a6b9.png)
系统和内核日志窗口太小
![image](https://user-images.githubusercontent.com/20243226/88002855-14736200-cb36-11ea-93f3-e72f905cb6d6.png)
passwall界面下字体过大
![image](https://user-images.githubusercontent.com/20243226/88002905-2fde6d00-cb36-11ea-91e9-6534aaed6e5c.png)
接口右边布局有点乱，如果可以向左挪动一点就好了

其他都挺完美了，希望可以考虑一下，谢谢，辛苦了

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88009093-42f83980-cb44-11ea-9ef1-390948a58710.png)
还有这里 只能显示一个字符

**Comment by kiddin9** [comment]
感谢反馈,进度条没效果这个是因为18.06的首页index.htm文件是lean的autocore提供的,他在这个文件里把样式都写在了行内且没有任何class标识,导致没办法添加效果

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88009253-a5e9d080-cb44-11ea-9ebf-556076c1e211.png)
这里左对齐效果会更好

**Comment by db-one** [comment]
> 感谢反馈,进度条没效果这个是因为18.06的首页index.htm文件是lean的autocore提供的,他在这个文件里把样式都写在了行内且没有任何class标识,导致没办法添加效果

感谢回复

**Comment by db-one** [comment]
> 感谢反馈,进度条没效果这个是因为18.06的首页index.htm文件是lean的autocore提供的,他在这个文件里把样式都写在了行内且没有任何class标识,导致没办法添加效果

https://github.com/kenzok8/openwrt-packages/tree/master/luci-theme-atmaterial
我不懂代码，你看他这个能不能参考一下
![image](https://user-images.githubusercontent.com/20243226/88009533-5952c500-cb45-11ea-9f72-b11e9d3cf908.png)
18.06进度条是有的

**Comment by kiddin9** [comment]
已修复,进度条也添加了样式,passwall我没有测试环境,暂时没有调整

**Comment by db-one** [comment]
OK，编译测试一下，希望晚点有时间可以把PASSWALL处理一下就更好了，辛苦了

**Comment by kiddin9** [comment]
@db-one 要不你把你编译好的带passwall的固件发我测试下.

**Comment by db-one** [comment]
https://github.com/db-one/OpenWrt-Actions-Lean-Lienol/actions/runs/176299729

这里你应该可以直接下载吧   我用actions编译的

**Comment by dolphinpaopao** [comment]
刚刚用最新源码编译完成发现有两个小细节需要完善。
1、概览页面ipv6位置显示不完整。
2、网络→接口页面，全屏状态下，删除的按钮显示不完整。浏览器chrome，显示器分辨率2560*1440。非全屏状态显示正常。
![概览ipv6](https://user-images.githubusercontent.com/20945941/88017779-f703bf80-cb58-11ea-915d-071eabcdd08a.jpg)
![网络接口](https://user-images.githubusercontent.com/20945941/88017791-fa974680-cb58-11ea-9000-729679e557bb.jpg)

**Comment by Aes64X** [comment]
> @db-one 要不你把你编译好的带passwall的固件发我测试下.

“”管控“图标缺失无须在意了。。。。我把那些页面全已到服务里了。

**Comment by db-one** [comment]
1806登陆页背景缺失
math.randomseed(os.time())
	local bgTable = glob("/www/luci-static/argon/img/*")
不清楚是不是这个源码路径没改的原因？/luasrc/view/themes/edge/header_login.htm

**Comment by db-one** [comment]
/www/luci-static/edge/目录下也没有img文件夹

**Comment by db-one** [comment]
看了下还不是img实现的，js？不懂，等修复吧

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88119935-5f53af00-cbf4-11ea-9f90-32bc6aa3f4d7.png)
自己编译的就是空白背景的，用你编译好的IPK安装就有背景图，不知道是什么原因

**Comment by kiddin9** [comment]
> ![image](https://user-images.githubusercontent.com/20243226/88119935-5f53af00-cbf4-11ea-9f90-32bc6aa3f4d7.png)
> 自己编译的就是空白背景的，用你编译好的IPK安装就有背景图，不知道是什么原因

是同一个固件么,

**Comment by db-one** [comment]
> > ![image](https://user-images.githubusercontent.com/20243226/88119935-5f53af00-cbf4-11ea-9f90-32bc6aa3f4d7.png)
> > 自己编译的就是空白背景的，用你编译好的IPK安装就有背景图，不知道是什么原因
> 
> 是同一个固件么,

是的  同一个固件 所以才感觉很奇怪，我把自己编译的主题卸载了  然后安装的你的IPK就背景正常，所以才很奇怪，求指点

另外我修改了一下css首页的两个颜色值
![image](https://user-images.githubusercontent.com/20243226/88125414-d6437480-cc01-11ea-8b3e-ef067c93d16d.png)
对比下面默认的，个人感觉更加美观一点，希望可以采纳，鼠标划过的颜色值没有改，只是改了默认颜色
![image](https://user-images.githubusercontent.com/20243226/88125392-c9268580-cc01-11ea-9f9c-67e16869f977.png)
background-color: rgba(223, 56, 18, 0.04);改成 
background-color: rgba(223, 56, 18, 0.02);

  background-color: #e5effd;
改成
  background-color: #f8fbfe;

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88125582-2a4e5900-cc02-11ea-9119-81862e3e9693.png)
来个全图对比
![image](https://user-images.githubusercontent.com/20243226/88125622-3e925600-cc02-11ea-8478-78928fae956d.png)

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88125712-75686c00-cc02-11ea-9663-ff8108987eb4.png)
鼠标划过

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88132944-61793600-cc13-11ea-9ac5-f33233d27f4e.png)
源码里面版本是

![image](https://user-images.githubusercontent.com/20243226/88133030-ab621c00-cc13-11ea-94f0-a1ffd0e23d63.png)

luci-theme-edge | 1.5-20200720

但是你发布的IPK版本号是
luci-theme-edge | 1.6-20200721

**Comment by kiddin9** [comment]
我减少了色块出现的次数,两个色块间全部由白色块隔开,应该会看起来好些了.
![image](https://user-images.githubusercontent.com/48883331/88133279-3e02bb00-cc14-11ea-989d-438d782c2569.png)

另外编译后的主题无登录背景问题应该也解决了.

**Comment by db-one** [comment]
好的  稍等再次编译一下试试看

**Comment by db-one** [comment]
新编译了  登录页还是无背景

**Comment by kiddin9** [comment]
@db-one 不好意思没修复好,又重新弄了下,这次应该不会有问题了

**Comment by db-one** [comment]
> @db-one 不好意思没修复好,又重新弄了下,这次应该不会有问题了

好的 辛苦了   希望抽空可以把PASSWALL适配一下，有两个地方有问题的
![image](https://user-images.githubusercontent.com/20243226/88158935-3a385e00-cc3f-11ea-8a34-e45d7a64eb40.png)
![image](https://user-images.githubusercontent.com/20243226/88158974-47554d00-cc3f-11ea-8d6f-8514da930559.png)
软件首页字体小点和排序按钮不显示，其他都自动适配的很完美了，首页的移动端也自适配的很完美，没有问题

**Comment by db-one** [comment]
好了 登录页背景出来了

**Comment by db-one** [comment]
passwall修复了？
![image](https://user-images.githubusercontent.com/20243226/88359527-8ac9cb80-cda5-11ea-8b4d-d802b8217297.png)
 看到主题有更新，PASSWALL正好也对界面有了大的更改，不知道那边的原因，反正现在是全适配了

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88359662-10e61200-cda6-11ea-82e0-4cb5434e7c97.png)
日志这里  之前没注意看 ，貌似还是窄啊@garypang13  你看下

**Comment by kiddin9** [comment]
@db-one passwall我有修复了下 日志窄是字体小吗 还是框框不够高

**Comment by db-one** [comment]
原来如此，大佬辛苦了
![image](https://user-images.githubusercontent.com/20243226/88360338-d8dfce80-cda7-11ea-966a-fe586246dd2f.png)
日志这里是框高度不够，应该把框的高度值去掉，让他自己适应浏览器页面高度，毕竟大家的浏览器分辨率不同，固定值的话，高分辨率显得高度低，低分辨率又显得高了

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88360547-b26e6300-cda8-11ea-8cb6-90d9cfe01886.png)
看起来是这个参数

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88360707-4b9d7980-cda9-11ea-8dac-0dbbad42cadd.png)
https://github.com/kenzok8/openwrt-packages/blob/master/luci-theme-atmaterial/htdocs/luci-static/atmaterial/css/style.css
他这个参数反而是15，不过其他地方参数有不一样的，你参考下，有的我看不明白是什么，不懂css
![image](https://user-images.githubusercontent.com/20243226/88360759-7a1b5480-cda9-11ea-9840-7451b5e70ad8.png)
这个是直接显示满屏的

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/88361942-5c4fee80-cdad-11ea-8d1c-1e30562fbe82.png)
![image](https://user-images.githubusercontent.com/20243226/88361945-5e19b200-cdad-11ea-9f14-b27f4b969faf.png)
这种日志类的框框貌似高度都不高，不过影响不大

**Comment by kiddin9** [comment]
好的,需要过段时间再修复,最近都在出差没法进路由后台调试,后者把这个页面另外为网页打包发我看下.

**Comment by db-one** [comment]
[OpenWrt - 日志 - LuCI_files.zip](https://github.com/garypang13/luci-theme-edge/files/4977046/OpenWrt.-.-.LuCI_files.zip)
你看下有没有参考价值

**Comment by db-one** [comment]
今天重置了一下系统，发现一个小问题
![image](https://user-images.githubusercontent.com/20243226/88479916-4137d700-cf85-11ea-8a16-75525cca7a53.png)
![image](https://user-images.githubusercontent.com/20243226/88479920-439a3100-cf85-11ea-8aad-73b2d70bad88.png)
通过连接添加节点时候不显示按钮
具体位置在
![image](https://user-images.githubusercontent.com/20243226/88479946-63315980-cf85-11ea-89d9-e61198d09af6.png)

**Comment by kiddin9** [comment]
日志高度和通过连接添加节点时候不显示按钮问题已修复.
