### ISSUE TITLE
“管控”图标缺失，提供源名称

### ISSUE THREAD

**Issue by Aes64X** [garypang13/luci-theme-edge#4]
“管控”菜单有些固件会带有
源名称如下图（Chrome 检查）：
![截图_20200721094404](https://user-images.githubusercontent.com/47932152/88003270-07a33e00-cb37-11ea-9142-d11b579566d9.png)

希望可以增加，多谢。

![截图_20200721034404](https://user-images.githubusercontent.com/47932152/88003340-38837300-cb37-11ea-9e82-0f5777f4c261.png)

**Comment by kiddin9** [comment]
增加图标还要编辑字体,这个管控菜单是Lienol的一些插件才有的,也不常用,以后还有新图标缺失再一起增加.

**Comment by Aes64X** [comment]
> 增加图标还要编辑字体,这个管控菜单是Lienol的一些插件才有的,也不常用,以后还有新图标缺失再一起增加.

多谢。
