### ISSUE TITLE
1907分支防火墙显示错乱

### ISSUE THREAD

**Issue by msylgj** [garypang13/luci-theme-edge#5]
如图所示, 防火墙这里前面显示过大,导致后面的下拉框和按钮都显示不正常  也有可能是patch导致的..full Cone应该是一个flagvalue  能否帮忙看一下是否可以优化
![image](https://user-images.githubusercontent.com/1388852/88095275-6fa16500-cbc7-11ea-96dc-6915e6ab60d1.png)

**Comment by kiddin9** [comment]
已修复

**Comment by msylgj** [comment]
感谢

**Comment by Lrvineshaw** [comment]
你好我想问一下lienol的master-dev分支也是用19.07吗？

**Comment by msylgj** [comment]
> 你好我想问一下lienol的master-dev分支也是用19.07吗？

应该是1806的
