### ISSUE TITLE
luci-theme-edge 18.06管控前面没有图标

### ISSUE THREAD

**Issue by ghost** [garypang13/luci-theme-edge#6]
luci-theme-edge 18.06管控前面没有图标，其他的前边都有，只有他没有感觉不够美观啊！

**Comment by kiddin9** [comment]
@vison9889 好的,下一版会修复.大概本月中旬

**Comment by ghost** [comment]
> @vison9889 好的,下一版会修复.大概本月中旬

感谢啦！

**Comment by db-one** [comment]
移动端目前不少地方布局可能都多少有点问题，有的影响操作，有的仅仅是不美观，希望可以一并处理了

**Comment by db-one** [comment]
目前atmaterial的各个移动界面处理的都比较合理，可以参考一下

**Comment by kiddin9** [comment]
已添加管控图标  移动界面优化过段时间再处理, 反正这主题用的人也不多...

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/91632450-3dc7bd80-ea13-11ea-99f7-a93cb50eb526.png)
![image](https://user-images.githubusercontent.com/20243226/91632458-47e9bc00-ea13-11ea-9ec9-d92496cf334e.png)

PC端流量监测右边重合了

**Comment by db-one** [comment]
自动刷新时间间隔选项   和  重置数据库

**Comment by kiddin9** [comment]
> ![image](https://user-images.githubusercontent.com/20243226/91632450-3dc7bd80-ea13-11ea-99f7-a93cb50eb526.png)
> ![image](https://user-images.githubusercontent.com/20243226/91632458-47e9bc00-ea13-11ea-9ec9-d92496cf334e.png)
> 
> PC端流量监测右边重合了

奇怪我这边并没有问题,你升级到最新主题试试.或者可能是18.06才有.
![image](https://user-images.githubusercontent.com/48883331/91682078-f2342180-eb82-11ea-8778-42ea8545f11a.png)

**Comment by db-one** [comment]
咱俩用的这个流量统计插件不是一个  我用的是LEAN大佬源码自带的
![image](https://user-images.githubusercontent.com/20243226/91784666-0553f980-ec36-11ea-95a3-27af53de039b.png)
三个小时前刚编译的

**Comment by X-Firefly** [comment]
谢谢，已经更新用上了。
