### ISSUE TITLE
18.06 脚本报错，横向滚动条。

### ISSUE THREAD

**Issue by nuintun** [garypang13/luci-theme-edge#9]
![批注 2020-09-14 075343](https://user-images.githubusercontent.com/1730277/93033818-7a79f280-f66a-11ea-97c4-3cadb4b2534b.png)
![批注 2020-09-14 074948](https://user-images.githubusercontent.com/1730277/93033820-7b128900-f66a-11ea-8fbe-ff1d345c9f36.png)
![企业微信截图_20200914091728](https://user-images.githubusercontent.com/1730277/93034059-608cdf80-f66b-11ea-9872-41aea9cca212.png)

PS: 横向滚动条看日志已修复，今天再测。

**Comment by kiddin9** [comment]
@nuintun 脚本报错已修复
